package token

// String returns a stable debug name for the token kind.
func (k Kind) String() string {
    switch k {
    case Unknown:
        return "Unknown"
    case EOF:
        return "EOF"
    case Ident:
        return "Ident"
    case Number:
        return "Number"
    case String:
        return "String"
    case Symbol:
        return "Symbol"
    case Assign:
        return "Assign"
    case Plus:
        return "Plus"
    case Minus:
        return "Minus"
    case Star:
        return "Star"
    case Slash:
        return "Slash"
    case Percent:
        return "Percent"
    case Bang:
        return "Bang"
    case Eq:
        return "Eq"
    case Ne:
        return "Ne"
    case Lt:
        return "Lt"
    case Gt:
        return "Gt"
    case Le:
        return "Le"
    case Ge:
        return "Ge"
    case And:
        return "And"
    case Or:
        return "Or"
    case Arrow:
        return "Arrow"
    case KwPackage:
        return "KwPackage"
    case KwImport:
        return "KwImport"
    case KwFunc:
        return "KwFunc"
    case KwReturn:
        return "KwReturn"
    case KwVar:
        return "KwVar"
    case KwDefer:
        return "KwDefer"
    case KwPipeline:
        return "KwPipeline"
    case KwIngress:
        return "KwIngress"
    case KwEgress:
        return "KwEgress"
    case KwError:
        return "KwError"
    case KwBool:
        return "KwBool"
    case KwByte:
        return "KwByte"
    case KwInt:
        return "KwInt"
    case KwInt8:
        return "KwInt8"
    case KwInt16:
        return "KwInt16"
    case KwInt32:
        return "KwInt32"
    case KwInt64:
        return "KwInt64"
    case KwInt128:
        return "KwInt128"
    case KwUint:
        return "KwUint"
    case KwUint8:
        return "KwUint8"
    case KwUint16:
        return "KwUint16"
    case KwUint32:
        return "KwUint32"
    case KwUint64:
        return "KwUint64"
    case KwUint128:
        return "KwUint128"
    case KwFloat32:
        return "KwFloat32"
    case KwFloat64:
        return "KwFloat64"
    case KwStringTy:
        return "KwString"
    case KwRune:
        return "KwRune"
    case LParenSym:
        return "LParen"
    case RParenSym:
        return "RParen"
    case LBraceSym:
        return "LBrace"
    case RBraceSym:
        return "RBrace"
    case LBracketSym:
        return "LBracket"
    case RBracketSym:
        return "RBracket"
    case CommaSym:
        return "Comma"
    case SemiSym:
        return "Semi"
    case DotSym:
        return "Dot"
    case ColonSym:
        return "Colon"
    case PipeSym:
        return "Pipe"
    case BackslashSym:
        return "Backslash"
    case DollarSym:
        return "Dollar"
    case TickSym:
        return "Tick"
    case TildeSym:
        return "Tilde"
    case QuestionSym:
        return "Question"
    case AtSym:
        return "At"
    case PoundSym:
        return "Pound"
    case CaretSym:
        return "Caret"
    case SingleQuoteSym:
        return "SingleQuote"
    case DoubleQuoteSym:
        return "DoubleQuote"
    case LineComment:
        return "LineComment"
    case BlockComment:
        return "BlockComment"
    default:
        return "Unknown"
    }
}
