name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.25'
          check-latest: true

      - name: Go vet
        run: go vet ./...

      - name: Go tests (all)
        run: make test

      - name: Coverage gate (changed packages)
        env:
          THRESHOLD: '0.80'
          # Skip packages regex
          SKIP_PKGS: '^github.com/sam-caldwell/ami/src/ami/visualize/ascii$|.*/experimental/.*'
          # Package-specific threshold overrides (comma-separated regex=threshold)
          PKG_THRESHOLDS: '^github.com/sam-caldwell/ami/src/ami/compiler/parser=0.90,^github.com/sam-caldwell/ami/src/ami/compiler/codegen/llvm=0.75'
          # Extra path excludes for changed-files detection (space/comma-separated)
          EXTRA_EXCLUDES: 'src/**/autogen/** src/**/third_party/**'
          BASE_REF: ${{ github.base_ref }}
        run: |
          bash scripts/coverage_gate.sh
